CREATE DATABASE FIRSTTODOAPI;
USE FIRSTTODOAPI;
CREATE TABLE TODO(
	iD INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID),
    TITLE VARCHAR(100),
    DONE BOOLEAN NOT NULL DEFAULT TRUE
);

DROP TABLE TODO;

INSERT INTO TODO(TITLE,DONE)
	VALUES('Primeira Tarefa',2),
		('Segunda Tarefa',0);

SELECT * FROM TODO;

INSERT INTO TODO(TITLE,DONE)
	VALUES('Terceira Tarefa',1);

SELECT * FROM TODO WHERE DONE IS TRUE;

UPDATE TODO SET DONE=TRUE WHERE ID=1;
UPDATE TODO SET TITLE='Segunda task' WHERE ID=2;
